In [ ]:
import torch
# The autograd package provides automatic differentiation 
# for all operations on Tensors

In [ ]:
# requires_grad = True -> tracks all operations on the tensor. 
x = torch.randn(3, requires_grad=True)
y = x + 2

In [ ]:
print (x)

a = y**3
b = torch.sqrt(a)
z= torch.exp(b)
z= z.sum()
z.backward()
print(x.grad)

a = y**3
b = torch.sqrt(a)
z= torch.exp(b)
z= z.mean()
z.backward()
print(x.grad)

a = y**3
b = torch.sqrt(a)
z= torch.exp(b)
z= z.sum()
z.backward()
print(x.grad)


tensor([ 0.1609,  0.3905, -0.7961], requires_grad=True)
tensor([331.4698, 523.3245,  72.8545])
tensor([349.0830, 554.4695,  74.9101])
tensor([401.9225, 647.9048,  81.0769])


In [ ]:
# y was created as a result of an operation, so it has a grad_fn attribute.
# grad_fn: references a Function that has created the Tensor
print(x) # created by the user -> grad_fn is None
print(y)
print(y.grad_fn)

tensor([ 0.1609,  0.3905, -0.7961], requires_grad=True)
tensor([2.1609, 2.3905, 1.2039], grad_fn=<AddBackward0>)


In [ ]:
z = y * y * 3
z= z.sum()
z.backward()
print(x.grad)

z = y * y * 3
z= z.mean()
z.backward()
print(x.grad)

z = y * y * 3
z= z.sum()
z.backward()
print(x.grad)


tensor([56.1835, 62.1534, 31.3011])
tensor([60.5053, 66.9345, 33.7089])
tensor([73.4707, 81.2776, 40.9322])


In [ ]:
# Do more operations on y
z = y * y * 3
print(z)
z = z.mean()
print(type(z))
print(z)

tensor([14.0085, 17.1437,  4.3480], grad_fn=<MulBackward0>)
<class 'torch.Tensor'>
tensor(11.8334, grad_fn=<MeanBackward0>)


In [ ]:
# Let's compute the gradients with backpropagation
# When we finish our computation we can call .backward() and have all the gradients computed automatically.
# The gradient for this tensor will be accumulated into .grad attribute.
# It is the partial derivate of the function w.r.t. the tensor

z.backward()
print(x.grad) # dz/dx


tensor([5.8708, 7.6800, 4.9293])


In [ ]:
# Generally speaking, torch.autograd is an engine for computing vector-Jacobian product
# It computes partial derivates while applying the chain rule

# -------------
# Model with non-scalar output:
# If a Tensor is non-scalar (more than 1 elements), we need to specify arguments for backward() 
# specify a gradient argument that is a tensor of matching shape.
# needed for vector-Jacobian product

x = torch.randn(3, requires_grad=True)

In [ ]:
y = x * 2
for _ in range(10):
    y = y * 2

print(y)
print(y.shape)

tensor([-1087.4006,  1971.4565,  4006.4727], grad_fn=<MulBackward0>)
torch.Size([3])


In [ ]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float32)
y.backward(v)
print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [ ]:
# -------------
# Stop a tensor from tracking history:
# For example during our training loop when we want to update our weights
# then this update operation should not be part of the gradient computation
# - x.requires_grad_(False)
# - x.detach()
# - wrap in 'with torch.no_grad():'

# .requires_grad_(...) changes an existing flag in-place.
a = torch.randn(2, 2)
print (a)
print(a.requires_grad)
b = ((a * 3) / (a - 1))
print (b)
print(b.grad_fn)
print (b.grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)
print(b)

tensor([[0.7428, 0.4621],
        [0.1757, 1.4226]])
False
tensor([[-8.6631, -2.5775],
        [-0.6395, 10.0996]])
None
None
True
tensor(2.8198, grad_fn=<SumBackward0>)


In [ ]:

# .detach(): get a new Tensor with the same content but no gradient computation:
a = torch.randn(2, 2, requires_grad=True)
print(a.requires_grad)
b = a.detach()
print(b.requires_grad)

True
False


In [ ]:
# wrap in 'with torch.no_grad():'
a = torch.randn(2, 2, requires_grad=True)
print(a.requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)


True
False


In [ ]:
# -------------
# backward() accumulates the gradient for this tensor into .grad attribute.
# !!! We need to be careful during optimization !!!
# Use .zero_() to empty the gradients before a new optimization step!
weights = torch.ones(4, requires_grad=True)

In [ ]:

for epoch in range(3):
    # just a dummy example
    model_output = (weights*3).sum()
    model_output.backward()
    
    print(weights.grad)

    # optimize model, i.e. adjust weights...
    with torch.no_grad():
        weights -= 0.1 * weights.grad

    # this is important! It affects the final weights & output
    weights.grad.zero_()

print(weights)
print(model_output)

# Optimizer has zero_grad() method
# optimizer = torch.optim.SGD([weights], lr=0.1)
# During training:
# optimizer.step()
# optimizer.zero_grad()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([0.1000, 0.1000, 0.1000, 0.1000], requires_grad=True)
tensor(4.8000, grad_fn=<SumBackward0>)
