In [131]:
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

In [132]:
# load dataset
df = pandas.read_csv("iris.csv")
X = df.iloc[:,0:4]
y = df.iloc[:,4]

In [133]:
df.shape, X.shape, y.shape

((150, 5), (150, 4), (150,))

In [134]:
y.sample(5)

128    Iris-virginica
102    Iris-virginica
107    Iris-virginica
9         Iris-setosa
6         Iris-setosa
Name: Species, dtype: object

In [136]:
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(y)

encoded_y = encoder.transform(y)
# convert integers to dummy variables (i.e. one hot encoded)
y = np_utils.to_categorical(encoded_y)

In [139]:
#target variable is encoded
y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [108]:
#Train Test Split
X_train , X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [109]:
# define baseline model
def baseline_model():
	# create model
	model = Sequential()
	model.add(Dense(8, input_dim=4, activation='relu'))
	model.add(Dense(3, activation='softmax'))
	# Compile model
	model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

In [110]:
estimator = KerasClassifier(build_fn=baseline_model, epochs=200, batch_size=5, verbose=0)

In [111]:
#Dataset is very small so lets use Kfold and Cross Validation for training
kfold = KFold(n_splits=10, shuffle=True)

In [112]:
#Train the model using Kfold corss validator
results = cross_val_score(estimator, X_train, dummy_y_train, cv=kfold)

In [140]:
#Let's check result of this training
print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Baseline: 97.50% (3.82%)


# Training without Cross Validation

In [141]:
model1 = baseline_model()

In [142]:
model1.fit(X_train, y_train, epochs=150, batch_size=10)

Epoch 1/150
12/12 [==============================] - 0s 998us/step - loss: 1.0028 - accuracy: 0.3750
Epoch 2/150
12/12 [==============================] - 0s 1ms/step - loss: 0.9201 - accuracy: 0.6167
Epoch 3/150
12/12 [==============================] - 0s 1ms/step - loss: 0.8621 - accuracy: 0.6917
Epoch 4/150
12/12 [==============================] - 0s 2ms/step - loss: 0.8252 - accuracy: 0.6917
Epoch 5/150
12/12 [==============================] - 0s 2ms/step - loss: 0.7790 - accuracy: 0.6917
Epoch 6/150
12/12 [==============================] - 0s 2ms/step - loss: 0.7351 - accuracy: 0.6917
Epoch 7/150
12/12 [==============================] - 0s 2ms/step - loss: 0.7128 - accuracy: 0.6917
Epoch 8/150
12/12 [==============================] - 0s 2ms/step - loss: 0.6951 - accuracy: 0.6917
Epoch 9/150
12/12 [==============================] - 0s 1ms/step - loss: 0.6799 - accuracy: 0.6917
Epoch 10/150
12/12 [==============================] - 0s 1ms/step - loss: 0.6658 - accuracy: 0.6917
Epoch 1

12/12 [==============================] - 0s 4ms/step - loss: 0.2637 - accuracy: 0.9667
Epoch 83/150
12/12 [==============================] - 0s 2ms/step - loss: 0.2605 - accuracy: 0.9667
Epoch 84/150
12/12 [==============================] - 0s 1ms/step - loss: 0.2574 - accuracy: 0.9667
Epoch 85/150
12/12 [==============================] - 0s 2ms/step - loss: 0.2554 - accuracy: 0.9667
Epoch 86/150
12/12 [==============================] - 0s 5ms/step - loss: 0.2522 - accuracy: 0.9667
Epoch 87/150
12/12 [==============================] - 0s 1ms/step - loss: 0.2510 - accuracy: 0.9667
Epoch 88/150
12/12 [==============================] - 0s 2ms/step - loss: 0.2473 - accuracy: 0.9667
Epoch 89/150
12/12 [==============================] - 0s 2ms/step - loss: 0.2447 - accuracy: 0.9667
Epoch 90/150
12/12 [==============================] - 0s 2ms/step - loss: 0.2424 - accuracy: 0.9667
Epoch 91/150
12/12 [==============================] - 0s 2ms/step - loss: 0.2409 - accuracy: 0.9667
Epoch 92/150


# Prediction on Testset

In [143]:
y_pred = model1.predict(X_test)

In [166]:
y_pred_f=[]
y_test_f=[]
for i in range( len(y_pred)):
    print ( np.round(y_pred[i],1), y_test[i])
    #print (  np.argmax(y_pred[i]), np.argmax(y_test[i]) )
    y_pred_f.append(np.argmax(y_pred[i]))
    y_test_f.append(np.argmax(y_test[i]))

[0. 0. 1.] [0. 0. 1.]
[0.  0.9 0.1] [0. 1. 0.]
[1. 0. 0.] [1. 0. 0.]
[0.  0.1 0.9] [0. 0. 1.]
[1. 0. 0.] [1. 0. 0.]
[0. 0. 1.] [0. 0. 1.]
[1. 0. 0.] [1. 0. 0.]
[0.  0.9 0.1] [0. 1. 0.]
[0.  0.8 0.1] [0. 1. 0.]
[0.  0.9 0.1] [0. 1. 0.]
[0.  0.2 0.8] [0. 0. 1.]
[0.  0.9 0.1] [0. 1. 0.]
[0.  0.8 0.2] [0. 1. 0.]
[0.  0.8 0.2] [0. 1. 0.]
[0.  0.7 0.3] [0. 1. 0.]
[1. 0. 0.] [1. 0. 0.]
[0.  0.7 0.3] [0. 1. 0.]
[0.  0.7 0.3] [0. 1. 0.]
[1. 0. 0.] [1. 0. 0.]
[1. 0. 0.] [1. 0. 0.]
[0.  0.1 0.9] [0. 0. 1.]
[0.  0.6 0.4] [0. 1. 0.]
[1. 0. 0.] [1. 0. 0.]
[1. 0. 0.] [1. 0. 0.]
[0.  0.3 0.7] [0. 0. 1.]
[1. 0. 0.] [1. 0. 0.]
[1. 0. 0.] [1. 0. 0.]
[0.  0.9 0.1] [0. 1. 0.]
[0.1 0.9 0. ] [0. 1. 0.]
[1. 0. 0.] [1. 0. 0.]


# Report on Test Set

In [162]:
from sklearn import metrics 
metrics.accuracy_score(y_test_f,y_pred_f)

1.0

In [164]:
print (metrics.classification_report(y_test_f, y_pred_f))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

