In [1]:
import numpy as np

# Create a word-word co-occurrence matrix
word_co_occurrences = np.array([
    [1, 2, 3],
    [2, 1, 4],
    [3, 4, 1]
])

# Perform SVD
U, S, Vh = np.linalg.svd(word_co_occurrences)

# Truncate the singular values
S_truncated = S[:2]

# Extract the word embeddings and context embeddings
word_embeddings = U[:, :2]
context_embeddings = Vh[:, :2]

# Print the word embeddings and context embeddings
print(word_embeddings)
print(context_embeddings)

[[-0.50578521 -0.25523155]
 [-0.58437383 -0.60130182]
 [-0.63457746  0.75716113]]
[[-0.50578521 -0.58437383]
 [ 0.25523155  0.60130182]
 [ 0.82403773 -0.54492509]]


In [2]:
U, S, Vh

(array([[-0.50578521, -0.25523155, -0.82403773],
        [-0.58437383, -0.60130182,  0.54492509],
        [-0.63457746,  0.75716113,  0.15497893]]),
 array([7.07467358, 3.1878826 , 0.88679099]),
 array([[-0.50578521, -0.58437383, -0.63457746],
        [ 0.25523155,  0.60130182, -0.75716113],
        [ 0.82403773, -0.54492509, -0.15497893]]))

In [4]:
word_embeddings, S_truncated, context_embeddings

(array([[-0.50578521, -0.25523155],
        [-0.58437383, -0.60130182],
        [-0.63457746,  0.75716113]]),
 array([7.07467358, 3.1878826 ]),
 array([[-0.50578521, -0.58437383],
        [ 0.25523155,  0.60130182],
        [ 0.82403773, -0.54492509]]))

In [6]:
np.dot(word_embeddings, S_truncated).dot(context_embeddings)

array([-1.03352026,  0.05905581])