In [ ]:
# https://trigonaminima.github.io/2019/09/seq2seq-components/

In [1]:
import torch

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
# Size of the dictionary
input_vocab_dim = 5

# Size of embedding
embedding_dim = 20

# Defining the embedding layer
embedding_layer = torch.nn.Embedding(input_vocab_dim, embedding_dim)
embedding_layer

Embedding(5, 20)

In [8]:
# A single sentence having 5 tokens
inp = torch.tensor([1, 2, 3, 4, 0])
print("input shape\t:", inp.shape)

# getting the vector for each token using the embedding layer
out = embedding_layer(inp)
print("output shape\t:", out.shape)
print(out)

input shape	: torch.Size([5])
output shape	: torch.Size([5, 20])
tensor([[-0.7936, -0.3694, -2.2462, -0.3501,  0.9411,  1.3482, -1.5945, -0.2848,
         -1.5984,  1.8343, -0.7797,  2.4953, -1.8779,  0.5689,  0.5575,  0.0792,
         -0.0257, -0.4618,  1.6969, -0.6920],
        [-0.9275,  0.2314, -1.4752, -1.1058,  0.5318, -0.4890,  0.5484, -1.3808,
          1.0538,  0.4202, -0.2142,  1.5913, -0.5671, -1.3922, -0.3418,  1.0664,
          0.3447,  1.2613, -0.9995,  0.6171],
        [-1.0413,  0.7199, -0.1844, -1.1252, -0.2217, -0.8503, -0.0885,  0.8040,
          0.5471,  0.9756,  0.8319,  0.0699,  0.0464, -0.7719, -1.3616, -0.3536,
          0.4984, -0.6923,  1.4699,  1.9522],
        [-0.6724, -0.7200, -1.6976,  0.8381,  0.4968,  1.3045,  1.3786, -0.2442,
          1.4999, -0.8292, -0.6534, -0.4635,  0.1908, -0.3466, -1.3314, -0.8776,
         -0.1733, -0.2740,  0.9191, -0.2694],
        [-2.2889, -0.0798, -0.3548, -0.4070, -0.5985, -0.1107,  0.9826, -1.8528,
         -0.2400,  1.0

In [32]:
inp = torch.tensor([1, 2, 3, 4, 0])
#inp = inp.unsqueeze(-2).repeat(1, 4)
print (inp.unsqueeze(1).repeat(2, 2))
# print (inp.unsqueeze(-1).repeat(1, 4))
# print (inp.unsqueeze(-0).repeat(1, 4))
# print (inp.unsqueeze(1).repeat(1, 4))

tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [0, 0]])


In [6]:
# Batch of 4 sentences having 5 tokens each.
# Batch size is 4. Max sentence len is 5
inp = torch.tensor([1, 2, 3, 4, 0])
inp = inp.unsqueeze(1).repeat(1, 4)
print("input shape\t:", inp.shape)

out = embedding_layer(inp)
print("output shape\t:", out.shape)
print(out[:, 0, :])

input shape	: torch.Size([5, 4])
output shape	: torch.Size([5, 4, 20])
tensor([[ 0.5190,  0.9007,  0.0715, -0.0533,  2.3561,  0.6038, -1.2878,  1.6617,
          0.1116,  1.5356, -0.1048, -0.9026,  0.6697,  0.1896, -2.0719,  1.3996,
         -1.7486,  0.2956,  0.5834,  1.5736],
        [-1.0988,  1.5844,  0.8863,  1.2622, -2.4835,  0.4523, -0.2453, -0.1435,
          0.2491,  1.9961,  0.5782,  0.4976,  0.0824, -1.4638, -0.8596, -1.4618,
         -0.6942,  0.0220,  0.5505,  0.6522],
        [ 0.2674, -0.5346,  0.4826, -0.0607,  1.0150, -0.3251, -1.7147, -1.1964,
          0.3118, -1.6229,  1.7451,  0.2504, -2.1438,  1.7510, -0.0342,  0.4912,
         -0.9735,  0.1809,  0.5701, -0.3027],
        [ 1.6448, -0.4897, -3.0118, -0.7430,  0.5627, -0.3496, -0.7087, -0.6954,
         -0.4083, -0.6753,  1.6638,  0.0630,  0.4756, -0.9732,  0.4381, -1.3869,
          0.8934, -2.5852, -1.3451,  1.0392],
        [ 0.0351,  1.2230, -0.6721, -1.5965,  0.0456, -0.2834,  0.1062,  1.5492,
          1.1866

In [12]:
dropout_probab = 0.5
dropout = torch.nn.Dropout(dropout_probab)
dropout

Dropout(p=0.5, inplace=False)

In [13]:
# A random tensor with 8 values
inp = torch.randn(8)
print("input shape\t:", inp.shape)
print("input tensor\t:", inp)

# getting the vector for each token using the embedding layer
out = dropout(inp)
print("\noutput shape\t:", out.shape)
print("output tensor\t:", out)

input shape	: torch.Size([8])
input tensor	: tensor([-1.0891, -0.3290,  0.3391,  0.2870,  0.7590,  0.9878,  1.2947,  0.1421])

output shape	: torch.Size([8])
output tensor	: tensor([-0.0000, -0.0000, 0.0000, 0.5740, 0.0000, 0.0000, 2.5893, 0.2841])


In [14]:
# a random tensor with 10 values
inp = torch.randn(5, 4, 20)
print("input shape\t:", inp.shape)

# getting the vector for each token using the embedding layer
out = dropout(inp)
print("output shape\t:", out.shape)

print("\nTotal cells in input\t:", 5*4*20)
print("Zero values in input\t:", torch.sum(inp==0.00))
print("Zero values in output\t:", torch.sum(out==0.00))

input shape	: torch.Size([5, 4, 20])
output shape	: torch.Size([5, 4, 20])

Total cells in input	: 400
Zero values in input	: tensor(0)
Zero values in output	: tensor(206)


In [15]:
input_dim = 5
hidden_dim = 15

lstm = torch.nn.LSTM(input_dim, hidden_dim)
lstm

LSTM(5, 15)

In [16]:
# Random input with shape - (1, 1, 5)
inp = torch.randn(1, 1, 5)
print("input shape\t:", inp.shape)

out, (hid, cell) = lstm(inp)
print("output shape\t:", out.shape)
print("hidden shape\t:", hid.shape)
print("cell shape\t:", cell.shape)

input shape	: torch.Size([1, 1, 5])
output shape	: torch.Size([1, 1, 15])
hidden shape	: torch.Size([1, 1, 15])
cell shape	: torch.Size([1, 1, 15])


In [17]:
# Random input with shape - (4, 1, 5)
inp = torch.randn(4, 1, 5)
print("input shape\t:", inp.shape)

out, (hid, cell) = lstm(inp)
print("output shape\t:", out.shape)
print("hidden shape\t:", hid.shape)
print("cell shape\t:", cell.shape)

input shape	: torch.Size([4, 1, 5])
output shape	: torch.Size([4, 1, 15])
hidden shape	: torch.Size([1, 1, 15])
cell shape	: torch.Size([1, 1, 15])


In [18]:
# Random input with shape - (4, 6, 5)
inp = torch.randn(4, 6, 5)
print("input shape\t:", inp.shape)

out, (hid, cell) = lstm(inp)
print("output shape\t:", out.shape)
print("hidden shape\t:", hid.shape)
print("cell shape\t:", cell.shape)

input shape	: torch.Size([4, 6, 5])
output shape	: torch.Size([4, 6, 15])
hidden shape	: torch.Size([1, 6, 15])
cell shape	: torch.Size([1, 6, 15])


In [20]:
input_dim = 5
hidden_dim = 15
num_layers = 2

lstm = torch.nn.LSTM(input_dim, hidden_dim, num_layers=num_layers, dropout=0.5)
lstm

LSTM(5, 15, num_layers=2, dropout=0.5)

In [21]:
# Random input with shape - (1, 1, 5)
inp = torch.randn(1, 1, 5)
print("input shape\t:", inp.shape)

out, (hid, cell) = lstm(inp)
print("output shape\t:", out.shape)
print("hidden shape\t:", hid.shape)
print("cell shape\t:", cell.shape)

input shape	: torch.Size([1, 1, 5])
output shape	: torch.Size([1, 1, 15])
hidden shape	: torch.Size([2, 1, 15])
cell shape	: torch.Size([2, 1, 15])


In [22]:
# Random input with shape - (4, 1, 5)
inp = torch.randn(4, 1, 5)
print("input shape\t:", inp.shape)

out, (hid, cell) = lstm(inp)
print("output shape\t:", out.shape)
print("hidden shape\t:", hid.shape)
print("cell shape\t:", cell.shape)

input shape	: torch.Size([4, 1, 5])
output shape	: torch.Size([4, 1, 15])
hidden shape	: torch.Size([2, 1, 15])
cell shape	: torch.Size([2, 1, 15])


In [23]:
# Random input with shape - (4, 6, 5)
inp = torch.randn(4, 6, 5)
print("input shape\t:", inp.shape)

out, (hid, cell) = lstm(inp)
print("output shape\t:", out.shape)
print("hidden shape\t:", hid.shape)
print("cell shape\t:", cell.shape)

input shape	: torch.Size([4, 6, 5])
output shape	: torch.Size([4, 6, 15])
hidden shape	: torch.Size([2, 6, 15])
cell shape	: torch.Size([2, 6, 15])


In [24]:
input_dim = 5
hidden_dim = 15

lstm = torch.nn.LSTM(input_dim, hidden_dim, bidirectional=True)
lstm

LSTM(5, 15, bidirectional=True)

In [25]:
# Random input with shape - (1, 1, 5)
inp = torch.randn(1, 1, 5)
print("input shape\t:", inp.shape)

out, (hid, cell) = lstm(inp)

print("output shape\t:", out.shape)
print("hidden shape\t:", hid.shape)
print("cell shape\t:", cell.shape)

input shape	: torch.Size([1, 1, 5])
output shape	: torch.Size([1, 1, 30])
hidden shape	: torch.Size([2, 1, 15])
cell shape	: torch.Size([2, 1, 15])


In [26]:
# Random input with shape - (4, 1, 5)
inp = torch.randn(4, 1, 5)
print("input shape\t:", inp.shape)

out, (hid, cell) = lstm(inp)
print("output shape\t:", out.shape)
print("hidden shape\t:", hid.shape)
print("cell shape\t:", cell.shape)

input shape	: torch.Size([4, 1, 5])
output shape	: torch.Size([4, 1, 30])
hidden shape	: torch.Size([2, 1, 15])
cell shape	: torch.Size([2, 1, 15])


In [27]:
# random input is of shape - (4, 6, 5)
inp = torch.randn(4, 6, 5)
print("input shape\t:", inp.shape)

out, (hid, cell) = lstm(inp)
print("output shape\t:", out.shape)
print("hidden shape\t:", hid.shape)
print("cell shape\t:", cell.shape)

input shape	: torch.Size([4, 6, 5])
output shape	: torch.Size([4, 6, 30])
hidden shape	: torch.Size([2, 6, 15])
cell shape	: torch.Size([2, 6, 15])


In [29]:
input_dim = 5
hidden_dim = 15

gru = torch.nn.GRU(input_dim, hidden_dim)
gru

GRU(5, 15)

In [30]:
# Random input with shape - (4, 6, 5)
inp = torch.randn(4, 6, 5)
print("input shape\t:", inp.shape)

out, hid = gru(inp)
print("output shape\t:", out.shape)
print("hidden shape\t:", hid.shape)

input shape	: torch.Size([4, 6, 5])
output shape	: torch.Size([4, 6, 15])
hidden shape	: torch.Size([1, 6, 15])


In [32]:
input_dim = 5
output_dim = 15

linear_layer = torch.nn.Linear(input_dim, output_dim)
linear_layer

Linear(in_features=5, out_features=15, bias=True)

In [35]:
# Random input with shape - (5)
inp = torch.randn(5)
print("input shape\t:", inp.shape)

out = linear_layer(inp)
print("output shape\t:", out.shape)

input shape	: torch.Size([5])
output shape	: torch.Size([15])


In [36]:
# Random input with shape - (1, 1, 5)
inp = torch.randn(1, 1, 5)
print("input shape\t:", inp.shape)

out = linear_layer(inp)
print("output shape\t:", out.shape)

input shape	: torch.Size([1, 1, 5])
output shape	: torch.Size([1, 1, 15])


In [37]:
# Random input with shape - (4, 1, 5)
inp = torch.randn(4, 1, 5)
print("input shape\t:", inp.shape)

out = linear_layer(inp)
print("output shape\t:", out.shape)

input shape	: torch.Size([4, 1, 5])
output shape	: torch.Size([4, 1, 15])


In [38]:
# Random input with shape - (4, 6, 5)
inp = torch.randn(4, 6, 5)
print("input shape\t:", inp.shape)

out = linear_layer(inp)
print("output shape\t:", out.shape)

input shape	: torch.Size([4, 6, 5])
output shape	: torch.Size([4, 6, 15])
