In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Reading the file
pima = pd.read_csv('pima_indian_diabetes.csv')

In [4]:
# Let's check the top 5 values
pima.head()

No_Times_Pregnant  Plasma_Glucose  Diastolic_BP  Triceps  Insulin   BMI  \
0                  1              89            66       23       94  28.1   
1                  0             137            40       35      168  43.1   
2                  3              78            50       32       88  31.0   
3                  2             197            70       45      543  30.5   
4                  1             189            60       23      846  30.1   

   Age  Diabetes  
0   21         0  
1   33         1  
2   26         1  
3   53         1  
4   59         1

### Question-1: After normalising all the continuous features which feature has the maximum median value?

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
# Putting feature variable to X
X = pima.drop(['Diabetes'],axis=1)

# Putting response variable to y
y = pima['Diabetes']

In [7]:
# Splitting the data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7,test_size=0.3,random_state=100)

In [8]:
features = ['No_Times_Pregnant', 'Plasma_Glucose', 'Diastolic_BP', 'Triceps','Insulin', 'BMI', 'Age']

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
scaler = MinMaxScaler()

In [11]:
X_train[features] = scaler.fit_transform(X_train[features])

In [12]:
X_train.describe()

No_Times_Pregnant  Plasma_Glucose  Diastolic_BP     Triceps  \
count         274.000000      274.000000    274.000000  274.000000   
mean            0.189352        0.474922      0.512226    0.415301   
std             0.187606        0.220506      0.154892    0.200289   
min             0.000000        0.000000      0.000000    0.000000   
25%             0.058824        0.307143      0.400000    0.250000   
50%             0.117647        0.450000      0.512500    0.415094   
75%             0.294118        0.621429      0.625000    0.566038   
max             1.000000        1.000000      1.000000    1.000000   

          Insulin         BMI         Age  
count  274.000000  274.000000  274.000000  
mean     0.174849    0.308958    0.220195  
std      0.147098    0.146812    0.235134  
min      0.000000    0.000000    0.000000  
25%      0.075812    0.212679    0.047619  
50%      0.134176    0.308793    0.119048  
75%      0.214801    0.391104    0.333333  
max      1.000000    1.000000    1.000000

50% quantile corrosponds to median and Dialostic_BP seems to have maximum median value.

### Question-2: Build the model using all the variables. What is the p value for Triceps?

In [13]:
import statsmodels.api as sm

In [14]:
logm1 = sm.GLM(y_train,(sm.add_constant(X_train)), family = sm.families.Binomial())
logm1.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:               Diabetes   No. Observations:                  274
Model:                            GLM   Df Residuals:                      266
Model Family:                Binomial   Df Model:                            7
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -122.11
Date:                Thu, 22 Apr 2021   Deviance:                       244.22
Time:                        14:57:02   Pearson chi2:                     264.
No. Iterations:                     5                                         
Covariance Type:            nonrobust                                         
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                -5.1878      0.756     -6.864      0.000      -6.669      -3.706
No_Times_Pregnant     1.5575      1.124      1.386      0.166      -0.645       3.760
Plasma_Glucose        5.7310      0.980      5.851      0.000       3.811       7.651
Diastolic_BP         -0.4826      1.125     -0.429      0.668      -2.687       1.722
Triceps               0.6859      1.027      0.668      0.504      -1.326       2.698
Insulin              -0.8890      1.222     -0.728      0.467      -3.283       1.505
BMI                   3.1620      1.470      2.151      0.031       0.281       6.043
Age                   1.5469      0.953      1.624      0.104      -0.321       3.414
=====================================================================================
"""

In [15]:
X_test[features] = scaler.transform(X_test[features])


In [20]:
 sm.add_constant(X_test[features])

const  No_Times_Pregnant  Plasma_Glucose  Diastolic_BP   Triceps  \
124    1.0           0.647059        0.707143         0.575  0.396226   
140    1.0           0.000000        0.364286         0.400  0.433962   
276    1.0           0.470588        0.314286         0.550  0.622642   
252    1.0           0.235294        0.492857         0.500  0.207547   
326    1.0           0.058824        0.314286         0.550  0.094340   
..     ...                ...             ...           ...       ...   
332    1.0           0.647059        0.571429         0.675  0.528302   
15     1.0           0.176471        0.228571         0.350  0.075472   
33     1.0           0.235294        0.521429         0.700  0.245283   
171    1.0           0.058824        0.278571         0.550  0.264151   
355    1.0           0.117647        0.464286         0.500  0.471698   

      Insulin       BMI       Age  
124  0.162455  0.308793  0.714286  
140  0.070999  0.376278  0.095238  
276  0.240674  0.433538  0.523810  
252  0.128761  0.218814  0.571429  
326  0.037304  0.026585  0.166667  
..        ...       ...       ...  
332  0.138387  0.206544  0.500000  
15   0.046931  0.134969  0.023810  
33   0.306859  0.345603  0.047619  
171  0.069795  0.157464  0.357143  
355  0.096270  0.427403  0.047619  

[118 rows x 8 columns]

### Question-3: Use RFE and choose 5 features, which two features are not selected by RFE?

In [47]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
from sklearn.feature_selection import RFE
rfe = RFE(logreg, 5)             # running RFE with 13 variables as output
rfe = rfe.fit(X,y)
print(rfe.support_)           # Printing the boolean results
print(rfe.ranking_) 

[ True  True False  True False  True  True]
[1 1 2 1 3 1 1]


In [48]:
X.columns[rfe.support_]

Index(['No_Times_Pregnant', 'Plasma_Glucose', 'Triceps', 'BMI', 'Age'], dtype='object')

## Practice Questions - II

In [3]:
diabetes_train.describe()

No_Times_Pregnant  Plasma_Glucose  Diastolic_BP     Triceps  \
count         314.000000      314.000000    314.000000  314.000000   
mean           -0.010433        0.064286     -0.003381    0.046437   
std             0.998059        1.010829      1.009553    1.026241   
min            -1.027899       -2.158972     -3.734229   -2.105793   
25%            -0.716511       -0.733214     -0.693278   -0.750769   
50%            -0.405123       -0.020335     -0.053078    0.081263   
75%             0.529042        0.749250      0.587122    0.818205   
max             4.265702        2.442338      3.147923    3.219211   

          Insulin         BMI         Age    Diabetes          id  
count  314.000000  314.000000  314.000000  314.000000  314.000000  
mean     0.034151    0.007444    0.029489    0.337580  199.519108  
std      1.048578    1.040755    1.035566    0.473639  113.102210  
min     -1.195339   -2.118234   -0.967063    0.000000    1.000000  
25%     -0.663118   -0.720186   -0.771000    0.000000  100.250000  
50%     -0.240287    0.009075   -0.378873    0.000000  198.500000  
75%      0.302452    0.638730    0.601445    1.000000  299.500000  
max      5.805571    4.839986    4.914842    1.000000  392.000000

In [4]:
import numpy as np
import pandas as pd
import json

from sklearn import datasets, linear_model, metrics

# read training data
diabetes_train = pd.read_csv("diabetes_train.csv")

# read test data 
diabetes_test = pd.read_csv("diabetes_test.csv")

# read the file containing actual labels (for computing scores)
actual_data = pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/PZ2x3L59Q1k7jbRv02BJJjjZY/sample_diabetes_actual.csv")


print(diabetes_train.head())
print(diabetes_test.head())
print(actual_data.head())

## WRITE YOUR CODE HERE ##

# create logistic regression object
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE
log_model = LogisticRegression()
rfe = RFE(log_model,7)


#  create x_train and y_train
x_train = diabetes_train.iloc[:, :7]
y_train = diabetes_train.iloc[:, 7]


# Fit the model
rfe =rfe.fit(x_train, y_train)


# make predictions
predictions = rfe.predict( x_train )


# Compute evaluation scores and round them off to two decimal places
# note that the test case may fail if the metrics are not rounded off 
confusionm = metrics.confusion_matrix(diabetes_train.iloc[:, 7],predictions)
TN = confusionm[0,0]
FP = confusionm[0,1]
FN = confusionm[1,0]
TP = confusionm[1,1]

accuracy_score = round( (TN+TP)/(TN+FP+FN+TP) ,2)
precision_score = round( TP / (TP+FP) ,2)
recall_score = round( TP / (TP + FN) , 2)
f1_score = round( 2 * precision_score * recall_score / (precision_score + recall_score), 2)

print(accuracy_score, precision_score, recall_score, f1_score)


# write the scores into the output file as a dictionary
# this code is already written for you
d = {'recall_score': recall_score,
    'f1_score': f1_score,
    'accuracy_score': accuracy_score,
	'precision_score': precision_score}
print(d)

# writing the dictionary to output file
# code is already written
with open('answers.txt', 'w') as file:
     file.write(json.dumps(d)) 

   No_Times_Pregnant  Plasma_Glucose  Diastolic_BP   Triceps   Insulin  \
0           0.217654       -1.057250      1.387373  1.697782 -0.858757   
1          -0.093734       -1.381286      0.907222  0.176352 -0.724124   
2          -0.716511       -1.024846     -1.333478 -0.394184 -0.471687   
3          -0.716511       -0.117546      1.227323  0.937067  0.538059   
4           0.217654        0.822158     -0.853328 -0.204005  1.362686   

        BMI       Age  Diabetes   id  
0  0.656517 -0.182809         0  322  
1  0.158485 -0.378873         1  341  
2 -1.122169 -0.771000         0  334  
3  1.780646 -0.182809         1  137  
4 -0.311089 -0.182809         1   97  
   No_Times_Pregnant  Plasma_Glucose  Diastolic_BP   Triceps   Insulin  \
0          -1.027899        0.530526     -0.693278 -1.154899  0.453914   
1           3.642925        0.433315     -0.053078  0.271441 -0.387542   
2          -0.405123       -0.571196      0.747172  1.507603  0.294037   
3           2.397372     

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [23]:
actual_data.head(5)

Diabetes   id
0         0   82
1         0  300
2         0   37
3         1  338
4         0  182

In [22]:
diabetes_test.head(5)

No_Times_Pregnant  Plasma_Glucose  Diastolic_BP   Triceps   Insulin  \
0          -1.027899        0.530526     -0.693278 -1.154899  0.453914   
1           3.642925        0.433315     -0.053078  0.271441 -0.387542   
2          -0.405123       -0.571196      0.747172  1.507603  0.294037   
3           2.397372        0.498122      0.267022 -0.299095 -0.101447   
4          -0.716511       -1.672918     -1.813628 -1.059810 -0.673637   

        BMI       Age   id  
0 -1.563284 -0.967063  262  
1  0.571140  1.189635   38  
2  0.087337 -0.182809  243  
3  0.428845  1.875858  318  
4 -1.805185 -0.869031   43

In [21]:
diabetes_train.head(5)

No_Times_Pregnant  Plasma_Glucose  Diastolic_BP   Triceps   Insulin  \
0           0.217654       -1.057250      1.387373  1.697782 -0.858757   
1          -0.093734       -1.381286      0.907222  0.176352 -0.724124   
2          -0.716511       -1.024846     -1.333478 -0.394184 -0.471687   
3          -0.716511       -0.117546      1.227323  0.937067  0.538059   
4           0.217654        0.822158     -0.853328 -0.204005  1.362686   

        BMI       Age  Diabetes   id  
0  0.656517 -0.182809         0  322  
1  0.158485 -0.378873         1  341  
2 -1.122169 -0.771000         0  334  
3  1.780646 -0.182809         1  137  
4 -0.311089 -0.182809         1   97

In [16]:
print (diabetes_train.shape)
print (diabetes_test.shape)
print (actual_data.shape)

(314, 9)
(314, 8)
(314, 2)


In [27]:
print (x_train.columns)
print (x_test.columns)

Index(['No_Times_Pregnant', 'Plasma_Glucose', 'Diastolic_BP', 'Triceps',
       'Insulin', 'BMI', 'Age'],
      dtype='object')
Index(['No_Times_Pregnant', 'Plasma_Glucose', 'Diastolic_BP', 'Triceps',
       'Insulin', 'BMI', 'Age', 'id'],
      dtype='object')


In [54]:
import numpy as np
import pandas as pd
 
import json

from sklearn import datasets, linear_model, metrics

# read training data
diabetes_train = pd.read_csv("diabetes_train.csv")

# read test data 
diabetes_test = pd.read_csv("diabetes_test.csv")

# read the file containing actual labels (for computing scores)
actual_data = pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/PZ2x3L59Q1k7jbRv02BJJjjZY/sample_diabetes_actual.csv")


# print(diabetes_train.head())
# print(diabetes_test.head())
# print(actual_data.head())

## WRITE YOUR CODE HERE ##

# create logistic regression object
log_model = LogisticRegression()

#  create x_train and y_train
x_train = diabetes_train.iloc[:, :7]
y_train = diabetes_train.iloc[:, 7]

x_test = diabetes_test.drop("id", axis=1)
y_test = actual_data.Diabetes

# Fit the model
log_model = log_model.fit(x_train, y_train)


# make predictions
predictions1 = log_model.predict(diabetes_test.iloc[:, :7])
predictions2 = log_model.predict(x_test)



# Compute evaluation scores and round them off to two decimal places
# note that the test case may fail if the metrics are not rounded off 
#confusionm = metrics.confusion_matrix(y_train, predictions)

accuracy_score = round( metrics.accuracy_score(y_train, predictions1), 2)
precision_score = round( metrics.precision_score (y_train, predictions1), 2)
recall_score = round( metrics.recall_score(y_train, predictions1), 2)
f1_score = round( metrics.f1_score(y_train, predictions1), 2)

print(accuracy_score, precision_score, recall_score, f1_score)

#accuracy_score = round( metrics.scorer.accuracy_score(y_test, predictions2), 2)
#precision_score = round( metrics.scorer.precision_score (y_test, predictions2), 2)
#recall_score = round( metrics.scorer.recall_score(y_test, predictions2), 2)
#f1_score = round( metrics.scorer.f1_score(y_test, predictions2), 2)

# write the scores into the output file as a dictionary
# this code is already written for you
d = {'recall_score': recall_score,
    'f1_score': f1_score,
    'accuracy_score': accuracy_score,
	'precision_score': precision_score}
print(d)

# writing the dictionary to output file
# code is already written
with open('answers.txt', 'w') as file:
     file.write(json.dumps(d)) 

0.58 0.35 0.26 0.3
{'recall_score': 0.26, 'f1_score': 0.3, 'accuracy_score': 0.58, 'precision_score': 0.35}


In [55]:
#Note: Please use the following command in your code after pandas import statement to make sure that your dataframe is printed properly:
pd.set_option('display.max_columns', 500)
#Missing this might lead to not all columns being printed and the correct code being rejected.


In [56]:
import pandas as pd

In [40]:
import pandas as pd 
pd.set_option('display.max_columns', 500)
df=pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/8NMooe4G0ENEe8z9q5ZvaZA7/googleplaystore.csv")
#add your cleaning code here
df.head(5)
#print(df.corr())

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone   
1     967   14M     500,000+  Free     0       Everyone   
2   87510  8.7M   5,000,000+  Free     0       Everyone   
3  215644   25M  50,000,000+  Free     0           Teen   
4     967  2.8M     100,000+  Free     0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up

In [7]:
import numpy as np

a= [[2,1,0,0],
[0,0,1,1],
[1,1,0,0],
[1,1,1,0]]

In [11]:
a =np.array(a)

In [24]:
print (a[1]*a[3])
print (a[0]*a[2])
print (a[0]*a[3])
print (a[1]*a[2])
print (a[1]*a[3])
print (a[2]*a[3])

[0 0 1 0]
[2 1 0 0]
[2 1 0 0]
[0 0 0 0]
[0 0 1 0]
[1 1 0 0]
