In [2]:
#paths required
datafolder_p = r'D:\18-DS\github\SDSHL\data\processed' #Change this when working on Nimblebox
datafolder_e = r'D:\18-DS\github\SDSHL\data\external'
datafolder_i = r'D:\18-DS\github\SDSHL\data\internal'
modelfolder  = r'D:\18-DS\data\models\BERT'
resultsfolder = r'D:\18-DS\github\SDSHL\data\results'

# vectorfolder_bert = modelfolder + r'\BERT'
# vectorfolder_ft   = modelfolder + r'\fasttext_wiki.hi'
# vectorfolder_standford = modelfolder + r'\POS-Tagger-Hindi'

filepath_train =datafolder_p+ r'\2-train.csv' #Change this when working on Nimblebox
filepath_test  =datafolder_p+ r'\2-test.csv'  #Change this when working on Nimblebox
filepath_fulldata = datafolder_p+ r'\2-Hinglish_Sarcasm_Clean.csv'

In [4]:
import pandas as pd
import numpy as np
import sys
import random as rn

import sklearn.metrics as metrics
from sklearn.naive_bayes import GaussianNB
#import sklearn.svm as svm
from sklearn.linear_model import LogisticRegression             
from sklearn.pipeline import Pipeline

from keras.preprocessing.sequence import pad_sequences



D:\Users\admin\anaconda3\lib\site-packages\transformers\modeling_auto.py:819: FutureWarning: The class `AutoModelWithLMHead` is deprecated and will be removed in a future version. Please use `AutoModelForCausalLM` for causal language models, `AutoModelForMaskedLM` for masked language models and `AutoModelForSeq2SeqLM` for encoder-decoder models.
  warnings.warn(


In [5]:
df_train = pd.read_csv(filepath_train, sep="\t")
df_test  = pd.read_csv(filepath_test, sep="\t")
df_full  = pd.read_csv(filepath_fulldata, sep="\t", index_col="ID")

X_train =  df_train['sentence'] 
y_train = df_train['label']

X_test =  df_test['sentence'] 
y_test = df_test['label']



In [6]:
X_train = list(X_train)
y_train = list(y_train)

X_test = list(X_test)
y_test = list(y_test)

len(X_train), len(y_train), len(X_test), len(y_test)

(1800, 1800, 200, 200)

In [8]:
from transformers import AutoTokenizer, AutoModelWithLMHead

gpt_tokenizer = AutoTokenizer.from_pretrained("gpt2-medium")

gpt_model = AutoModelWithLMHead.from_pretrained("gpt2-medium")

D:\Users\admin\anaconda3\lib\site-packages\transformers\modeling_auto.py:819: FutureWarning: The class `AutoModelWithLMHead` is deprecated and will be removed in a future version. Please use `AutoModelForCausalLM` for causal language models, `AutoModelForMaskedLM` for masked language models and `AutoModelForSeq2SeqLM` for encoder-decoder models.
  warnings.warn(


In [7]:
gpt_transformer = (gpt_tokenizer, gpt_model, max_length=200)
#classifier = svm.LinearSVC(C=1.0, class_weight="balanced")
#classifier = LogisticRegression()
classifier = GaussianNB()

model_pipeline_gpt2 = Pipeline(
    [
        ("vectorizer", gpt_transformer),
        ("classifier", classifier),
    ]
)
model_pipeline_indic.fit(X_train, y_train)

NameError: name 'gpt_transformer' is not defined

In [ ]:
https://github.com/Hari-thapliyal/SDSHL/blob/master/docs/final/Dissertation.pdf

In [1]:
from transformers import GPT2Tokenizer
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer("Hello world")['input_ids']

tokenizer(" Hello world")['input_ids']


[18435, 995]

In [4]:
tokenizer("हरि हिरन राम")['input_ids']

[11976,
 117,
 11976,
 108,
 11976,
 123,
 28225,
 117,
 11976,
 123,
 11976,
 108,
 11976,
 101,
 28225,
 108,
 48077,
 11976,
 106]

In [6]:
from transformers import GPT2Tokenizer, TFGPT2LMHeadModel
import tensorflow as tf

tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = TFGPT2LMHeadModel.from_pretrained('gpt2', return_dict=True)

inputs = tokenizer("Hello, my dog is cute", return_tensors="tf")
outputs = model(inputs)
logits = outputs.logits

All model checkpoint weights were used when initializing TFGPT2LMHeadModel.

All the weights of TFGPT2LMHeadModel were initialized from the model checkpoint at gpt2.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.


In [7]:
outputs, inputs, logits

(TFCausalLMOutputWithPast(loss=None, logits=<tf.Tensor: shape=(1, 6, 50257), dtype=float32, numpy=
 array([[[ -35.236286,  -35.326637,  -38.975395, ...,  -44.464554,
           -43.997494,  -36.458054],
         [-112.6171  , -114.583176, -116.57247 , ..., -119.0128  ,
          -118.8059  , -111.69172 ],
         [ -88.743454,  -89.86434 ,  -93.19766 , ...,  -92.38388 ,
           -96.17824 ,  -92.12732 ],
         [ -85.16462 ,  -88.337944,  -92.8703  , ...,  -99.80171 ,
           -94.76569 ,  -90.93295 ],
         [-116.72806 , -119.39497 , -121.72591 , ..., -129.10034 ,
          -124.61023 , -121.609215],
         [ -77.442505,  -80.44625 ,  -88.04972 , ...,  -96.256386,
           -93.634514,  -84.06659 ]]], dtype=float32)>, past_key_values=(<tf.Tensor: shape=(2, 1, 12, 6, 64), dtype=float32, numpy=
 array([[[[[-1.25259566e+00,  2.31998491e+00,  1.72185048e-01, ...,
            -1.00761116e+00, -1.89699322e-01,  1.32189846e+00],
           [-1.64824724e+00,  3.02215242e+00,  1.2